### PR TITLE
Bpowers/improve module resolution

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by marimeireles** [comment]
@serge-sans-paille should we merge this so we can release a new version of memestra with this fix? Or do you need something else?
Thanks!

**Comment by serge-sans-paille** [comment]
I still need to spend some time on it, to add tests for instance ;-)

**Comment by marimeireles** [comment]
Right, thanks for the reply Serge =)

**Comment by serge-sans-paille** [comment]
Looks good now \o/ @brendan0powers can you check if it matches your expectations?

**Comment by brendan0powers** [comment]
This looks good to me. Unfortunately, I won't be able to test it until Monday.

**Pull request merged**
