### PR TITLE
Support looking for cache files in package directory

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
cc @SylvainCorlay

**Comment by serge-sans-paille** [comment]
and cc @JohanMabille

**Comment by serge-sans-paille** [comment]
@brendan0powers | @SylvainCorlay I'll happily take your review on that one.

**Review by brendan0powers — APPROVED** [review]
This looks good to me. I can give it a real-world test on Monday.

**Comment by brendan0powers** [comment]
Was able to test it this morning, and it seems to work as I'd expect.

**Comment by serge-sans-paille** [comment]
Thanks @brendan0powers for testing it!

**Comment by fasiha** [comment]
I noticed https://memestra.readthedocs.io/en/latest/memestra-cache.html still has the outdated docs, could I trouble someone to update that? Thank you 🙇!

**Pull request merged**
