### PR TITLE
Setup caching mechanism

### PR DESCRIPTION
**Pull request by serge-sans-paille**
This avoids to reprocess the same imports over and over.
It also paves the way for other import mechanism :-)

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@JohanMabille / @SylvainCorlay this one is now ready for review

**Comment by serge-sans-paille** [comment]
@JohanMabille up?

**Comment by JohanMabille** [comment]
Sorry, I've been swamped with other tasks to complete. I have one more bug to fix and I can start looking at this PR.

**Comment by JohanMabille** [comment]
Nice!

**Pull request merged**
