### PR TITLE
Switch to GH actions and pytest

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by JohanMabille** [comment]
Please no GH actions a long as we cannot restart only failing builds.

**Comment by davidbrochart** [comment]
I also wanted to try GH actions because the tests fail locally but pass on Travis CI.
Interestingly, one test fails on GH actions (see https://github.com/davidbrochart/memestra/runs/706803043), but it's not the same as the ones failing locally:
```
=================================== FAILURES ===================================
__________________________ TestCaching.test_defaults ___________________________

self = <test_caching.TestCaching testMethod=test_defaults>

    def test_defaults(self):
        tmpdir = tempfile.mkdtemp()
        try:
            os.environ['XDG_CONFIG_HOME'] = tmpdir
            cache = memestra.caching.Cache()
            key = memestra.caching.CacheKey(__file__)
            self.assertNotIn(key, cache)
            cache[key] = {}
            data = cache[key]
            self.assertEqual(data['version'], memestra.caching.Format.version)
>           self.assertEqual(data['name'], 'caching')
E           AssertionError: 'test_caching' != 'caching'
E           - test_caching
E           ? -----
E           + caching

tests/test_caching.py:41: AssertionError
```

**Comment by serge-sans-paille** [comment]
Please remove the README change from the commit list, it's not related and makes the diff bigger.

**Comment by davidbrochart** [comment]
Closing as this was not a CI issue and should be fixed in #17.

**Pull request closed without merging**
